language: python
sudo: required
dist: trusty
env:
    - PYVER=3.7
before_install:
    - sudo apt-get install graphviz
    - wget http://repo.continuum.io/miniconda/Miniconda${PYVER:0:1}-latest-Linux-x86_64.sh
        -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda env create -f test-environment.yml
    - source activate pysbjupyter-test
install:
    - pip install .
script:
    - pytest --nbval --cov=viz-pysb-widget
after_success:
    coveralls
notifications:
  slack: lopezlab:mKQHRW1hyvJVLCX8ZWSgwhRY