{% set data = load_setup_py_data() %}

package:
  name: "{{ data.get('name')|lower }}"
  version: {{ data.get('version') }}

source:
  source:
  git_url: https://github.com/LoLab-VU/pyvipr.git

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - ipywidgets >=7.0.0
    - matplotlib >=3.0.2
    - networkx >=2.2
    - numpy >=1.15.4
    - pip
    - python
    - python-louvain >=0.13
    - sympy >=1.3
  run:
    - ipywidgets >=7.0.0
    - matplotlib >=3.0.2
    - networkx >=2.2
    - numpy >=1.15.4
    - python
    - python-louvain >=0.13
    - sympy >=1.3

test:
  imports:
    - pyvipr
    - pyvipr.examples_models

about:
  home: https://github.com/LoLab-VU/pyvipr
  license: MIT 
  summary: Jupyter widget for the dynamic and static visualizations of 
           systems biology models written in PySB, BNGL, and SBML.
  doc_url: https://pyvipr.readthedocs.io

extra:
  recipe-maintainers:
    - ortega2247
