name: pysbjupyter-test
channels:
  - conda-forge
  - alubbock
dependencies:
  - python=3.7
  - traitlets
  - traittypes
  - jupyter
  - pysb
  - atomizer
  - coveralls
  - pytest
  - nbval
  - pytest-cov
  - pip:
      - python-louvain