name: pyvipr-test
channels:
  - conda-forge
  - alubbock
dependencies:
  - python=3.6
  - pip
  - traitlets
  - traittypes
  - jupyter
  - pysb
  - atomizer
  - matplotlib
  - networkx
  - coveralls
  - pytest
  - nbval
  - pytest-cov
  - pip:
      - tellurium
      - python-louvain