name: pysbViz_docs
channels:
  - conda-forge
  - alubbock
dependencies:
  - python=3.6
  - traitlets=>4.3.2
  - traittypes=>0.2.1
  - widgetsnbextension=>3.5.1
  - pysb=>1.9
  - pip=>19.2.2
  - nbsphinx=>0.5.0
  - pip:
      - tellurium
      - pyvipr
      - python-louvain