name: pysbViz_docs
channels:
  - conda-forge
  - alubbock
dependencies:
  - python=3.6
  - traitlets
  - traittypes
  - widgetsnbextension
  - jupyter_sphinx
  - pysb
  - pip
  - nbsphinx
  - pip:
      - tellurium
      - pyvipr
      - python-louvain