name: pysbviz
channels:
  - conda-forge
  - alubbock
dependencies:
  - python=3.6
  - jupyter
  - pysb
  - atomizer
  - graphviz
  - pip
  - pip:
      - tellurium
      - python-louvain
      - pyvipr