name: build
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@master
    - name: Setup conda
      uses: s-weigand/setup-conda@master
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge, alubbock
    - name: Install dependencies
      run: |
           conda install --yes pip traitlets traittypes jupyter pysb atomizer matplotlib networkx coveralls pytest nbval pytest-cov 'coverage<5'
           pip install tellurium
           pip install python-louvain
    - name: Install PyViPR and Test with pytest
      run: |
        pip install .
        pytest --nbval --cov=pyvipr
    - name: Create distribution
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      run: python setup.py sdist bdist_wheel
    - name: Publish package to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && matrix.os == 'macOS-latest'
      uses: ortega2247/pypi-upload-action@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
