name: build
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@master
    - name: Setup conda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
           pip install tellurium
           conda install --yes pip traitlets traittypes jupyter pysb atomizer matplotlib networkx coveralls pytest nbval pytest-cov 'coverage<5' python-louvain -c alubbock -c conda-forge
    - name: Install PyViPR and Test with pytest
      shell: bash -l {0}
      run: |
        python -m pip install .
        pytest --nbval --sanitize-with docs/pytest-sanitize.ini --cov=pyvipr
    - name: Create distribution
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && matrix.os == 'macOS-latest' && matrix.python-version == 3.7
      shell: bash -l {0}
      run: python setup.py sdist bdist_wheel
    - name: Publish package to PyPI
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && matrix.os == 'macOS-latest' && matrix.python-version == 3.7
      uses: ortega2247/pypi-upload-action@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
